#ifndef INCLUDES_H
#define INCLUDES_H
#include"funciones/registrar_clientes.c"
#include"funciones/listar_clientes.c"
#include"funciones/registrar_servicios.c"
#include"funciones/listar_servicios.c"
#include"funciones/detalles_clientes.c"
#include"funciones/generador_id.c"
#include"funciones/seleccionar_servicio.c"
#include"funciones/verificacion_dni.c"
#include"funciones/modificar_clientes.c"
#include"funciones/modificar_servicios.c"
#include"funciones/fecha.c"
#include"funciones/modificar_servicios_clientes.c"
#include"funciones/fecha_funciones.c"
#include"funciones/listar_contrataciones.c"
#include"funciones/listar_operaciones.c"
#include"funciones/generador_facturas.c"
#include"funciones/pago_facturas.c"
#include"funciones/estado_cliente.c"
#include"funciones/puesto.c"
#include"funciones/mayor_contratacion.c"
#include"funciones/generador_txt.c"
#include"funciones/buscador_id_dni.c"
#include"funciones/realizar_descuento.c"
#include"funciones/globales.c"
#include"funciones/listar_contratos_de_cliente.c"

#endif //INCLUDES_H